# Server
server:
  port: 8080

# Datasource
spring:
  datasource:
    url: jdbc:postgresql://localhost:32768/notification_service_db
    username: notification_service_user
    password: notification_service_user
  jpa:
    properties:
      hibernate:
        show-sql: true
